%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: m
%% Source: /net/isildur/ldisk/daily_build/r14b02_prebuild_opu_o.2011-03-14_20/otp_src_R14B02/lib/ic/examples/pre_post_condition/ex.idl
%% IC vsn: 4.2.26
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(M_HRL).
-define(M_HRL, true).


-record(m_NotAnInteger, {'OE_ID'="IDL:m/NotAnInteger:1.0"}).


-endif.


