%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNaming_BindingIterator
%% Source: /net/isildur/ldisk/daily_build/r14b02_prebuild_opu_o.2011-03-14_20/otp_src_R14B02/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.2.26
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNAMING_BINDINGITERATOR_HRL).
-define(COSNAMING_BINDINGITERATOR_HRL, true).




-endif.


