%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventChannelAdmin_TypeError
%% Source: /net/isildur/ldisk/daily_build/r14b02_prebuild_opu_o.2011-03-14_20/otp_src_R14B02/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.2.26
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventChannelAdmin_TypeError').
-ic_compiled("4_2_26").


-include("CosEventChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventChannelAdmin/TypeError:1.0",
                   "TypeError",[]}.

%% returns id
id() -> "IDL:omg.org/CosEventChannelAdmin/TypeError:1.0".

%% returns name
name() -> "CosEventChannelAdmin_TypeError".



