%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: erlang_binary
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r14b.2010-09-13_19/otp_src_R14B/lib/ic/include/erlang.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module(erlang_binary).
-ic_compiled("4_2_25").


-include("erlang.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_sequence,tk_octet,0}.

%% returns id
id() -> "IDL:erlang/binary:1.0".

%% returns name
name() -> "erlang_binary".



