%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: erlang
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r14b.2010-09-13_19/otp_src_R14B/lib/ic/include/erlang.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ERLANG_HRL).
-define(ERLANG_HRL, true).


-record(erlang_pid, {node, num, serial, creation}).
-record(erlang_port, {node, id, creation}).
-record(erlang_ref, {node, id, creation}).


-endif.


