%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CORBA
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r14b.2010-09-13_19/otp_src_R14B/lib/orber/src/CORBA.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_CORBA_HRL).
-define(OE_CORBA_HRL, true).




-endif.


