%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosPropertyService_PropertiesIterator
%% Source: /net/isildur/ldisk/daily_build/r14b02_prebuild_opu_o.2011-03-14_20/otp_src_R14B02/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.2.26
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSPROPERTYSERVICE_PROPERTIESITERATOR_HRL).
-define(COSPROPERTYSERVICE_PROPERTIESITERATOR_HRL, true).




-endif.


