%%% This file was automatically generated by snmpc_mib_to_hrl version 4.19
%%% Date: 14-Mar-2011::20:16:50
-ifndef('OTP-TC').
-define('OTP-TC', true).

%% Oids

-define(otpTcModule, [1,3,6,1,4,1,193,19,1,1,2]).


%% Range values


%% Default values

-endif.
