%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_erlang
%% Source: /net/isildur/ldisk/daily_build/r14b02_prebuild_opu_o.2011-03-14_20/otp_src_R14B02/lib/ic/include/erlang.idl
%% IC vsn: 4.2.26
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_ERLANG_HRL).
-define(OE_ERLANG_HRL, true).




-endif.


