%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_OrberIFR
%% Source: /net/isildur/ldisk/daily_build/r14b02_prebuild_opu_o.2011-03-14_20/otp_src_R14B02/lib/orber/src/OrberIFR.idl
%% IC vsn: 4.2.26
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_ORBERIFR_HRL).
-define(OE_ORBERIFR_HRL, true).




-endif.


