%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_Control
%% Source: /net/isildur/ldisk/daily_build/r14b02_prebuild_opu_o.2011-03-14_20/otp_src_R14B02/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.26
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_CONTROL_HRL).
-define(COSTRANSACTIONS_CONTROL_HRL, true).




-endif.


