%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_InvalidControl
%% Source: /net/isildur/ldisk/daily_build/r14b02_prebuild_opu_o.2011-03-14_20/otp_src_R14B02/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.26
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_InvalidControl').
-ic_compiled("4_2_26").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/InvalidControl:1.0",
                   "InvalidControl",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/InvalidControl:1.0".

%% returns name
name() -> "CosTransactions_InvalidControl".



