%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosPropertyService_PropertySet
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r14b.2010-09-13_19/otp_src_R14B/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSPROPERTYSERVICE_PROPERTYSET_HRL).
-define(COSPROPERTYSERVICE_PROPERTYSET_HRL, true).




-endif.


