#!/usr/bin/ruby

pkg_path = File.expand_path(File.join(File.dirname(__FILE__), "..", "pkg"))
project_name = ARGV[0]
version = ARGV[1]
arch = ARGV[2] == "x86_64" ? "amd64" : "i386"
deb_path = "#{pkg_path}/#{project_name}_#{version}-1_#{arch}"
system("mkdir -p #{deb_path}/opt")
system("cp -r #{File.dirname(__FILE__)}/DEBIAN #{deb_path}")
system("perl -pi -e 's/VERSION/#{version}/g' #{deb_path}/DEBIAN/control")
system("cp -r /opt/opscode #{deb_path}/opt")
system("chown -R root.root #{deb_path}/opt")
system("cd #{pkg_path} && dpkg-deb --build #{project_name}_#{version}-1_#{arch}")
system("rm -rf #{deb_path}")
