%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin
%% Source: /net/isildur/ldisk/daily_build/r14b02_prebuild_opu_o.2011-03-14_20/otp_src_R14B02/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.2.26
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_HRL).
-define(COSEVENTCHANNELADMIN_HRL, true).


-record('CosEventChannelAdmin_AlreadyConnected', {'OE_ID'="IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0"}).
-record('CosEventChannelAdmin_TypeError', {'OE_ID'="IDL:omg.org/CosEventChannelAdmin/TypeError:1.0"}).


-endif.


