%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm_PullSupplier
%% Source: /net/isildur/ldisk/daily_build/r14b02_prebuild_opu_o.2011-03-14_20/otp_src_R14B02/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.26
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_PULLSUPPLIER_HRL).
-define(COSEVENTCOMM_PULLSUPPLIER_HRL, true).




-endif.


