%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm
%% Source: /net/isildur/ldisk/daily_build/r14b02_prebuild_opu_o.2011-03-14_20/otp_src_R14B02/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.26
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_HRL).
-define(COSEVENTCOMM_HRL, true).


-record('CosEventComm_Disconnected', {'OE_ID'="IDL:omg.org/CosEventComm/Disconnected:1.0"}).


-endif.


