%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_NotifySubscribe
%% Source: /net/isildur/ldisk/daily_build/r14b02_prebuild_opu_o.2011-03-14_20/otp_src_R14B02/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.2.26
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_NOTIFYSUBSCRIBE_HRL).
-define(COSNOTIFYCOMM_NOTIFYSUBSCRIBE_HRL, true).




-endif.


