%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventChannelAdmin
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r14b.2010-09-13_19/otp_src_R14B/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCHANNELADMIN_HRL).
-define(OE_COSEVENTCHANNELADMIN_HRL, true).




-endif.


