%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyFilter_FilterNotFound
%% Source: /net/isildur/ldisk/daily_build/r14b02_prebuild_opu_o.2011-03-14_20/otp_src_R14B02/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.2.26
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyFilter_FilterNotFound').
-ic_compiled("4_2_26").


-include("CosNotifyFilter.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyFilter/FilterNotFound:1.0",
                   "FilterNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyFilter/FilterNotFound:1.0".

%% returns name
name() -> "CosNotifyFilter_FilterNotFound".



