%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: m_i
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r14b.2010-09-13_19/otp_src_R14B/lib/ic/examples/pre_post_condition/ex.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(M_I_HRL).
-define(M_I_HRL, true).




-endif.


